version: '3.8'

services:
    web:
        container_name: phpunit_dashboard
        build:
            context: "."
            target: dev
            args:
                DDE_UID: ${DDE_UID}
                DDE_GID: ${DDE_GID}
        volumes:
            - ./:/var/www
            #- ./var/phpunit_output:/var/www/var/phpunit_output
        environment:
            - VIRTUAL_HOST=phpunit.test
            - OPEN_URL=http://phpunit.test/

networks:
    default:
        name: "dde"
        external: true
