version: '3.8'
services:
    web:
        build:
            context: .
            target: dev
        environment:
            - 'DATABASE_URL=mysql://root:root@mariadb/phpunit_dashboard?serverVersion=11.8.0-MariaDB&charset=utf8'
        volumes:
            - './:/var/www'
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.phpunit-test-web.rule=Host(`phpunit.test`)'
            - 'traefik.http.routers.phpunit-test-web-tls.rule=Host(`phpunit.test`)'
            - 'traefik.http.routers.phpunit-test-web-tls.tls=true'
