version: '3.8'

services:
    web:
        container_name: phpunit_dashboard
        build:
            context: "." # Build directory
            target: dev # Build stage
            args:
                DDE_UID: ${DDE_UID} # Pass your UID (DDE_UID is set automatically)
                DDE_GID: ${DDE_GID} # Pass your GID (DDE_GID is set automatically)s
        volumes:
            - ./:/var/www
        environment:
            - VIRTUAL_HOST=phpunit.test
            - OPEN_URL=http://phpunit.test/

networks:
    default:
        name: "dde"
        external: true
