araise_crud_bundle:
    resource: "@araiseCrudBundle/Resources/config/routing.yml"
    prefix: /

araise_crud_dashboard:
    path: /dashboard
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /
        permanent: true
