araise_crud_bundle:
    resource: "@araiseCrudBundle/Resources/config/routing.yml"
    prefix: /

dashboard:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /dashboard
        permanent: true
